### ISSUE TITLE
review groupby advanced questions

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#117]
In https://github.com/h2oai/db-benchmark/issues/60 we proposed new advanced groupby questions.
5 new questions has been added, q6-q10, stressing some more advanced functionalities.
4 of those 5 new questions were focused on stressing expression to be evaluated by group.
5th question was focused on high cardinality grouping, rather than actual by-group computation.
So far sounds good.
The problem is that 4 out of 5 questions happens to be very low cardinality grouping. All 4 questions do grouping by `id2,id4` which for all `k` cases is low cardinality. Moreover it doesn't scale up with data size. We are getting following number of groups for 1e9 rows input:
[k=1e2 unsorted](https://h2oai.github.io/db-benchmark/groupby/plots/G1_1e9_1e2_0_0.advanced.png): 10'000 groups
[k=1e1 unsorted](https://h2oai.github.io/db-benchmark/groupby/plots/G1_1e9_1e1_0_0.advanced.png): 4 groups
[k=2e0 unsorted](https://h2oai.github.io/db-benchmark/groupby/plots/G1_1e9_2e0_0_0.advanced.png): 100 groups
[k=1e2 sorted](https://h2oai.github.io/db-benchmark/groupby/plots/G1_1e9_1e2_0_1.advanced.png): 10'000 groups
Number of groups are constant for across data sizes (1e7, 1e8, 1e9) for corresponding `k`, while it should scale up with data size. Only id3 and id6 will scale here.

I propose to change grouping columns in 2 or 3 questions so the cardinality of groupings can be more widely explored by different values of `k` factor.
@nalimilan @bkamins @mattdowle
Comments are more than welcome!

**Comment by bkamins** [comment]
I think it is OK.

As a side question - when you get "out of memory" error do you have an information at which stage the process failed?

**Comment by jangorecki** [comment]
yes, they are documented as comment in the code, from where the actual exceptions are stored for benchplot, in benchplot-dict.R file: https://github.com/h2oai/db-benchmark/blob/d4486ac8b2af3a6e20b5b3b98c6cf945c3a97a7c/benchplot-dict.R#L146

**Comment by bkamins** [comment]
Thank you!

**Comment by jangorecki** [comment]
by amending grouping columns as follows
```r
median v3 sd v3 by id4 id5
max v1 - min v2 by id3
largest two v3 by id6
regression v1 v2 by id2 id4
sum v3 count by id1:id6
```
the k=1e2 gives now
```
q6: 10000
q7: 10000000
q8: 20000000
q9: 10000
q10: 1000000000
```

**Comment by nalimilan** [comment]
Thanks for asking, but TBH I don't have a strong opinion.

**Comment by jangorecki** [comment]
In the question 8 we are getting top 2 rows by group. Before the change there were no rows having just single group, now testing changes proposed here I am getting
```jl
ANS = by(x, [:id6], largest2_v3 = :v3 => x -> partialsort(x, 1:2, rev=true)
#BoundsError: attempt to access 1-element Array{Float64, 1} at index [1:2]
```
@nalimilan @bkamins any tips how to handle that nicely, as `head(., n=2)` in R

**Comment by nalimilan** [comment]
I guess something like this would do:
```julia
ANS = by(x, [:id6], largest2_v3 = :v3 => x -> partialsort(x, 1:min(2, length(x)), rev=true)
```
