### ISSUE TITLE
cudf groupby q6 median

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#121]
median was added in cudf (https://github.com/rapidsai/cudf/pull/2905), when it will get published (0.11) and we will move to this release, we should also add q6.

**Comment by jangorecki** [comment]
also we should use this https://github.com/rapidsai/cudf/issues/2468 after upgrade to 0.11

**Comment by jangorecki** [comment]
upgrade to 0.11.0 did not solve this issue because median and std are not yet supported in groupby:
https://github.com/rapidsai/cudf/issues/3429 https://github.com/rapidsai/cudf/issues/3736

**Comment by rnyak** [comment]
@jangorecki is  groupby `median` supported in 0.12 stable or 0.13 nightly?

**Comment by jangorecki** [comment]
@rnyak I am not developing cudf, just using it, please see linked issues for status and if needed ask question in cudf repo.
For now cudf is not even run on benchmark because it can very easily corrupt memory driver context. Once that happens machine needs a full reboot. For details see https://github.com/h2oai/db-benchmark/issues/129
To address that I am waiting for cudf documentation.

**Comment by jangorecki** [comment]
It was already implemented, should be released as 0.13.
