### ISSUE TITLE
Data generation for join queries fails for 1e9 rows

### ISSUE THREAD

**Issue by amyskov** [h2oai/db-benchmark#153]
Command
Rscript _data/join-datagen.R 1e9 1e2 0 0
fails with next message:
Producing match data of 1e9 rows
Error in saveRDS(DT, dataf) : error writing to connection
Execution halted

**Comment by jangorecki** [comment]
Thank you for reporting.
Could you ensure you can write to your temp?
```r
saveRDS(iris, f<-tempfile(fileext="RDS"))
readRDS(f)
```

**Comment by amyskov** [comment]
Data was successfully written to the temp file, but i have found, that my /tmp storage (that is default storage for temporary files) is space limited and adding additional argument tmpdir=<my_tmp_dir_without_space_limit> to all tempfile functions in _data/join-datagen.R file solves my problem. Thanks for your response!
