### ISSUE TITLE
Question about pandas join benchmark setup

### ISSUE THREAD

**Issue by ivirshup** [h2oai/db-benchmark#156]
https://github.com/h2oai/db-benchmark/blob/7adc04352d458410536be1e08f509ad4dc06eb72/pandas/join-pandas.py#L30-L42

I'm a little confused about this code in the pandas join benchmark.

First, why are the same columns being converted to categorical repeatedly? Should this be happening to different dataframes?

Second, why convert integer values to categorical values? I'd understand this for string values, but doing this seems slower than just using the integer values.

**Comment by jangorecki** [comment]
Thanks for spotting that. That conversation should obviously be on each table, not repeatedly on `x` table.

id1:id3 are string, id4:id6 are integer.

**Comment by ivirshup** [comment]
Is the data used for this generated by `_data/join-datagen.R`? For me, that generates data where `id1:id3` are integers, `id4:id6` are strings and `v*`  columns are floats.

**Comment by jangorecki** [comment]
You are absolutely correct. I mixed that with groupby data where leading columns are categorical type. Thank you very much.

**Comment by jangorecki** [comment]
Report was rerun but because of this pandas version was already run it was not refreshed now. New timings will be refreshed after new pandas version release. Or if I force rerun it, but for a couple weeks I am not having workstation to do this.

**Comment by ivirshup** [comment]
Thanks for the quick responses on this!

**Comment by jangorecki** [comment]
Let's keep this issue open till timings will be updated on the report.

**Comment by jangorecki** [comment]
Pandas version got updated in the meantime so timings are now refreshed using categoricals properly. Thanks again.
