### ISSUE TITLE
Is the use of mean consistent across tools?

### ISSUE THREAD

**Issue by MichaelChirico** [h2oai/db-benchmark#157]
I am looking at the benchmark and the performance of `spark` on a task involving _only_ mean aggregation stands out -- is Spark by chance not doing the error correction double-pass that's done in R and `data.table` as well?

If so that would seem to give an (IMO) unfair advantage to tools that give numerically inferior results.

At the least this could be pointed out somewhere (I don't see it mentioned anywhere in the repo thus far).

**Comment by jangorecki** [comment]
Afair DT does not do double pass, just R does.
It make sense to use an ordinary mean, and if it is not available, then IMO it should be made available.

**Comment by MichaelChirico** [comment]
I see, I think I was mistaken in thinking GForce is doing double pass. But found this open issue:

https://github.com/Rdatatable/data.table/issues/1970

**Comment by jangorecki** [comment]
You can do a 2 pass algorithm using rollmean with n equal to length of x, and algo exact :)
