### ISSUE TITLE
upgrade underlying platforms

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#168]
- [x] R to 4.0.3
- [x] julia to 1.5.3
- [x] cudf + review if some of the previously not yet implemented functionalities are now available
- [ ] ~~python?~~ @st-pasha any idea if it make sense to upgrade python from 3.6? while 3.6 is a little bit old, it is supported well by all tools. Any idea which version should be preferred so that pandas, spark, dask, modin, pydt, etc. will work? 3.7, 3.8?

**Comment by st-pasha** [comment]
Many python libraries are dropping support for python 3.5, which lacked 2 important features compared to python 3.6: predictable dictionaries and f-strings. At the same time, python 3.7, 3.8 and 3.9 did not any critically important  features, so there is no urgent desire to move away from 3.6. In fact, I know of at least one library (sphinx) that performs noticeably better under 3.6 than under 3.8. So I would say there is no much point in moving away from 3.6 at this point.

**Comment by jangorecki** [comment]
Thank you
