### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by t-wojciech** [h2oai/db-benchmark#181]
Have you thought about publishing the benchmark results in a publication so that they could be cited? I would personally be interested in such a reference. For example, you might consider [The R Journal](https://journal.r-project.org/) as they accept benchmark articles.

**Comment by jangorecki** [comment]
Not really. I think that benchmark report url and project repository url could be used for citation as well. I don't see writing publication about db-benchmark anytime soon so I am going to close this issue.
