### ISSUE TITLE
duckdb join fails after upgrade to 0.2.6

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#207]
https://github.com/duckdb/duckdb/issues/1739
affects all join scripts, not just NA data cases

**Comment by Alex-Monahan** [comment]
Could DuckDB 0.2.7 solve your issue? Is there a way to trigger a re-run with the new version? Thanks!

**Comment by jangorecki** [comment]
The canonical way to rerun is, as of now, ping me on GitHub, email, etc. Unfortunately the machine is also used for another project, therefore benchmark run is not scheduled now to run routinely. I am running it manually from time to time when other project is using machine.
Problem in this issue has been resolved by new duckdb so closing.
