### ISSUE TITLE
Understanding timing of DataFrames.jl joins

### ISSUE THREAD

**Issue by bkamins** [h2oai/db-benchmark#210]
Hi @jangorecki,

Frankly speaking I was expecting the join benchmarks to be better than they are now. Of course what you report are hard facts, so there is nothing to discuss with. However, I thought of running your benchmarks for `N=10^8` on some machine in the cloud. I have used with 40GB of RAM (so less than you have) and running it on one thread. The timings for the Question 1 I get are:
```
julia> nrow(x)
100000000

julia> nrow(small)
100

julia> GC.gc(false); @time innerjoin(x, small, on = :id1, makeunique=true, matchmissing=:equal);
  8.954664 seconds (327 allocations: 5.253 GiB)

julia> GC.gc(false); @time innerjoin(x, small, on = :id1, makeunique=true, matchmissing=:equal);
  8.403870 seconds (327 allocations: 5.253 GiB)
```

While in your reports the timings are: 88 seconds and 51 seconds. So clearly we have some problem in DataFrames.jl. Is there some way to diagnose the the root cause of such a big difference? (I know it is most likely problematic on your side, but maybe you could suggest something so that we can identify what slows us down?) Thank you!

**Comment by bkamins** [comment]
Also the wildly different timings between runs are super strange (compilation time is clearly not the reason as in 0.5GB case we can see that compilation is quite fast)

**Comment by jangorecki** [comment]
Thanks for tracking that. Agree, we need to check that well. I will start by checking timings when running interactively.

**Comment by bkamins** [comment]
A rather weak machine:
```
root@bk:~# free
              total        used        free      shared  buff/cache   available
Mem:       41096776      438780    28603192       14856    12054804    40111960
Swap:       1532372           0     1532372
root@bk:~# lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       2
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           61
Model name:                      Intel Core Processor (Broadwell)
Stepping:                        2
CPU MHz:                         2199.998
BogoMIPS:                        4399.99
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        8 MiB
L3 cache:                        32 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disabled, RSB filling
Vulnerability Srbds:             Unknown: Dependent on hypervisor status
Vulnerability Tsx async abort:   Vulnerable: Clear CPU buffers attempted, no microcode; SMT Host state unknown
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtsc
                                 p lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe p
                                 opcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjus
                                 t bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat
```

**Comment by bkamins** [comment]
I have investigated the problem a bit more on my laptop (specs at the bottom):

I used the following setup
```
Rscript join-datagen.R 5e7 0 0 0 ## 1e7
```
CC @qunnj and @nalimilan to keep things in one place

Here are the timings on 4 threads data.table vs DataFrames.jl:
```
> system.time(x[small, on="id1", nomatch=NULL])
   user  system elapsed 
 76.502   1.803  69.806 
> system.time(x[small, on="id1", nomatch=NULL])
   user  system elapsed 
  9.864   1.768   3.562 
> system.time(x[small, on="id1", nomatch=NULL])
   user  system elapsed 
 10.228   1.799   3.647 
```
vs
```
 julia> GC.gc(false); @time innerjoin(x_df, small_df, on = :id1, makeunique=true, matchmissing=:equal);
 29.788014 seconds (1.99 M allocations: 2.657 GiB, 82.67% gc time, 8.77% compilation time)

julia> GC.gc(false); @time innerjoin(x_df, small_df, on = :id1, makeunique=true, matchmissing=:equal);
 26.933888 seconds (424 allocations: 2.546 GiB, 90.35% gc time)

julia> GC.gc(false); @time innerjoin(x_df, small_df, on = :id1, makeunique=true, matchmissing=:equal);
  8.081725 seconds (427 allocations: 2.546 GiB, 69.88% gc time)
```
This case is close to available RAM bound.
It seems that occasionally data.table also has issues with GC then (the first run).
However, the point is that Julia is spending most of the time in GC. In general we plan resolve this issue systematically in DataFrames.jl, but the timings indicate that in the tests on your machine for 10^8 case Julia also must do GC many times in the process. However, it should not happen if your machine has 100GB+ RAM (I have discussed with people from Julia dev team who work on GC) as GC should normally not be triggered at all if you use less than 75% of RAM (this is the test above where I run 10^8 data on 40GB machine and as you can see there GC is not triggered at all and the timings are good).

So the question is - how it is possible that on your machine GC gets triggered given it has so much RAM and the data should occupy only like 20% of it. If this is indeed the case then there is a serious issue with Julia GC (so it would be really good to have a report on it even if we will be able to work around this in JuliaData ecosystem which seems possible).

In general - excluding GC I would normally in 10^8 expect timings similar to what we see in 10^7 tests, as the algorithms we use scale linearly with data.

Machine:
```
~$ free
              total        used        free      shared  buff/cache   available
Mem:       16142120     1659912    12097292      625212     2384916    13529856
Swap:       2097148       18432     2078716
~$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           142
Model name:                      Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
Stepping:                        10
CPU MHz:                         800.090
CPU max MHz:                     4000.0000
CPU min MHz:                     400.0000
BogoMIPS:                        3999.93
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-7
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse ss
                                 e2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopol
                                 ogy nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtp
                                 r pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3
                                 dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vp
                                 id ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt x
                                 saveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flu
                                 sh_l1d
```

**Comment by bkamins** [comment]
@jangorecki - it would be also valuable for us if you could merge https://github.com/h2oai/db-benchmark/pull/211 and re-run the DataFrames.jl tests. #211 disables using multi-threading in CSV reading which seems to be a part of the reasons of our GC problems (previously we have not tested Julia multi-threaded CSV reader on your machine as threading was disabled). In particular if we see a significant difference here this will be a signal for us that something in CSV parser needs to be fixed. Thank you!

CC @quinnj

**Comment by jangorecki** [comment]
Will try disabling multiple threads in CSV reader.
Is there any way to write debug info (ideally to a file) of GC?
In R there is very similar problem, but it occurs only on 1e9 and k=2 #110 and then GC takes 90+% of time

**Comment by bkamins** [comment]
Yes - the `@timed` macro does this:
```
julia> @timed rand(10^6)
(value = [0.2879010030414526, 0.827605838353122, 0.16047861784468398, 0.659463018379433, 0.5980844199486031, 0.48018232841299646, 0.942479313315683, 0.15985895771971426, 0.5894205947170248, 0.018663543308293118  …  0.38017892472842796, 0.5450891933761659, 0.838110233103023, 0.4818441208541653, 0.6409645912615927, 0.15698126242025623, 0.7521267843869184, 0.17315725842444873, 0.8024951697319784, 0.5160260542856592], time = 0.004318269, bytes = 8000080, gctime = 0.0, gcstats = Base.GC_Diff(8000080, 1, 0, 1, 0, 0, 0, 0, 0))
```
and you get there all details of what GC did (the `gcstats` field).

Actually @quinnj works on resolving this issue in full (hopefully in a few weeks), but for the time being disabling threading is a half-measure that might help a bit.

**Comment by jangorecki** [comment]
Timings after #211 are on the report. Speed up is pretty big, and for groupby as well, but according to your report it is still not ideal. Do you think you could tweak julia join script, so extra debugging info would go to a file that I can later send to you for analysis?

**Comment by bkamins** [comment]
Thank you for running these benchmarks. I think we currently know what is going on (thank you for running these benchmarks).

In around 2 weeks we should have an improved CSV.jl version that will be more GC-friendly. Then I will let you know and ask if you could kindly re-run the tests.

The `groupby` performance is improved because of https://github.com/JuliaData/DataFrames.jl/pull/2749 (we have enabled multi-threading in 1.0 release so there were some corner cases we did not handle correctly, especially making GC work well with multi-threading).

I think it can be closed for now. Thank you!
