### ISSUE TITLE
add `modin` (pandas on ray) as new solution

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#22]
Installing modin force python to uninstall recent pandas and install pandas 0.22.0.
@st-pasha should we use separate virtual env for pandas and modin? maybe also another one for pydatatable?
```
Installing collected packages: pyyaml, funcsigs, flatbuffers, click, redis, ray, pandas, modin
  Found existing installation: pandas 0.23.0
    Uninstalling pandas-0.23.0:
      Successfully uninstalled pandas-0.23.0
Successfully installed click-6.7 flatbuffers-2015.12.22.1 funcsigs-1.0.2 modin-0.1.1 pandas-0.22.0 pyyaml-3.13 ray-0.5.0 redis-2.10.6
```

**Comment by st-pasha** [comment]
I'd say yes -- virtual environments are easy to create, and we should definitely test against the latest pandas version.

**Comment by jangorecki** [comment]
modin is so far capable only to `sort`, grouping and joining is not yet implemented. `modin` solution was added, and python environments were re-designed to use private virtualenv for every solution that uses python, so we now have `pandas/py-pandas`, `pydatatable/py-pydatatable` and `modin/py-modin` virtual envs which are sourced before running script of each of those tools.
