### ISSUE TITLE
Why Spark produces performance data based on csv dataset

### ISSUE THREAD

**Issue by Tom-Deng** [h2oai/db-benchmark#235]
The performance of Spark based on the csv dataset is not optimal, but the current performance data of Spark is based on the csv dataset. What is the author's consideration?

**Comment by jangorecki** [comment]
Do you mean that Spark is not dealing well with CSV data?
It loads the data into memory so CSV is just a source for data. Later on spark operates on an in-memory object and not the CSV.

**Comment by Tom-Deng** [comment]
> Do you mean that Spark is not dealing well with CSV data? It loads the data into memory so CSV is just a source for data. Later on spark operates on an in-memory object and not the CSV.
Spark has specifically optimized parquet files. Take q1 of 5G data groupby operation as an example，spark processing csv dataset takes 8.42s on average. but spark processing parquet dataset takes 555ms on average. 
csv data:
![image](https://user-images.githubusercontent.com/17919002/139834709-bf69691f-26c5-4912-a249-64325ff4d900.png)
parquet data:
![image](https://user-images.githubusercontent.com/17919002/139834803-a8063bad-d8a5-4b77-8df3-804d28def7a0.png)[](url)

**Comment by jangorecki** [comment]
Thanks for investigation. You should try to cache data in memory before running first query, as we do in benchmark script. As of now your code is probably including time to load data from csv in the time of query.

**Comment by Tom-Deng** [comment]
> Thanks for investigation. You should try to cache data in memory before running first query, as we do in benchmark script. As of now your code is probably including time to load data from csv in the time of query.
Refer to the suggestions above，I try to cache data in memory before running first query，but the result is basically the same.
![image](https://user-images.githubusercontent.com/17919002/140475410-cccd8e3b-6b7e-4dd0-ac9e-a0a2ddc76186.png)

**Comment by jangorecki** [comment]
I don't think that your code caches data in memory. Spark interface is lazy and AFAIR calling persist alone does not force computation.

**Comment by Tom-Deng** [comment]
> I don't think that your code caches data in memory. Spark interface is lazy and AFAIR calling persist alone does not force computation.

See my code in the attachment, you can take a look at it as a whole. 
[spark_csv_vs_parquet.ipynb.zip](https://github.com/h2oai/db-benchmark/files/7502343/spark_csv_vs_parquet.ipynb.zip)

**Comment by jangorecki** [comment]
It may be easier if you just run db-benchmark script having data source replaced and compare timings.

**Comment by jangorecki** [comment]
It may be easier if you just run db-benchmark script having data source replaced and compare timings.

**Comment by Tom-Deng** [comment]
> It may be easier if you just run db-benchmark script having data source replaced and compare timings.
Caching data in memory，the performance of csv and parquet is indeed similar in db-benchmark's scense.
