### ISSUE TITLE
add total time took by each task to report

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#27]
now report has only groupby so postpone that when two tasks will be there. currently the time was put by hand.

**Comment by mattdowle** [comment]
It would be nice to place the timing in seconds at the end of each bar, too.   Say  "7.3s; 7.1s" in small text at the end of each bar for the 1st and 2nd timing.  Just to read off the timings extremely easily and conveniently.

**Comment by jangorecki** [comment]
total timing is already added on the bottom based on the logs related to presented benchmarks
