### ISSUE TITLE
report needs to display more dimensions

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#32]
kind of "browser" UI selector, currently report has selector for data size only.
Over time we will need to select:
- task (groupby, join, rollfun, ...)
- data (so we can present different K in groupby benchmark)
- number of rows
- multiple data/datasizes for 2+ tables tasks (join)
- batch (to view historical benchmarks)

**Comment by jangorecki** [comment]
good example of functionality we need can browser of clickhouse benchmark results: https://clickhouse.yandex/benchmark.html

**Comment by st-pasha** [comment]
I think a good starting point would be to make [at least some of the] content to be dynamically generated. So, instead of [or in addition to] the pre-rendered static images, we could load the CSV with all benchmark results, and then display the charts using one of the JS libraries such as flot.js.

**Comment by jangorecki** [comment]
This is good idea, but more for ad-hoc exploration of benchmark timings data. As we won't get such a well explaining graphics in generic plotting library.
Currently our plot have:
- legend with solutions in order of total timing for both of runs of all questions
- by question timings, solutions ordered by first run timings
- first and second timing easy to compare
- syntax for each tool next to timing bar
- cutting off longer timings
- small things like solutions version, approximate cost of running in cloud, useful information on labels

Ad-hoc exploration is not what most of viewers expect to see when arriving to this page. On average user spends 58 seconds on website at the current moment, we should focus to provide summary compact enough to fit into that time .

**Comment by jangorecki** [comment]
- [x] task (groupby, join, rollfun, ...) - solved by tabsets
- [x] data (so we can present different K in groupby benchmark) - solved by links from the bottom ref table
- [x] number of rows - solved by nested tabsets
- [x] multiple data/datasizes for 2+ tables tasks (join) - solved by design of questions where RHS size is just another question
- [ ] batch (to view historical benchmarks) - no plans for now
