### ISSUE TITLE
Order results within each test, perhaps.

### ISSUE THREAD

**Issue by mattdowle** [h2oai/db-benchmark#34]
Each software is already colored, and the syntax is next to each bar,  so if they are ordered by time within each test it might be easier to more quickly compare and it won't be difficult to identify which software is which.   Question is, what to order by:  first run time, or average of both, or total of both runs.   As more packages are added,  ordering within test might become more needed.   As always, providing a toggle to let the viewer choose the sort method that is appropriate for them would be ideal, but more work to achieve of course.

**Comment by jangorecki** [comment]
currently solutions are in alphabetical order

**Comment by st-pasha** [comment]
It is useful to have a stable order between different questions. On the other hand, alphabetical is too arbitrary. We could order the packages by the geometric mean of their timings across all questions -- this would have almost the same result as Matt's suggestion, while avoiding the packages switching their order in different questions.

**Comment by st-pasha** [comment]
> Why precisely?

Otherwise it will confuse colorblind people, and it also goes against the advice of UX experts (https://ux.stackexchange.com/questions/109019/should-a-bar-chart-redraw-categories-in-size-order-or-stay-fixed-position)

**Comment by mattdowle** [comment]
@st-pasha  That's why I wrote above : 
> There are no y-axis labels currently: if the software names could be added there, it wouldn't be necessary to know the colors or read the syntax to know which was which: it would be easier. But apparently there's a width constraint of the page to overcome.

Where "to overcome" meant @jangorecki please overcome :-) and add product name to y-axis.
