### ISSUE TITLE
Force consistent sort order for spark?

### ISSUE THREAD

**Issue by MichaelChirico** [h2oai/db-benchmark#42]
I guess related to #12.

It's possible part of Spark's advantage is because it doesn't constrain itself to return groups in the same order as they're fed in. Would require a separate query for `by = ` functionality in other languages as well. 

The query to force this would be substantially more complicated and might slow down Spark. 

Also related: https://github.com/Rdatatable/data.table/issues/1880

Also, it's probably a bug that `spark` gets away with using `group by` and not `group by order by` at the moment...

**Comment by jangorecki** [comment]
We had small discussion on order of results in this benchmark tasks and conclusion was to use the faster one for each solution, so to ignore the order of rows in the answer. If all solutions would provide api for retaining group and returning in order than it make more sense to have both as separate tests.
