### ISSUE TITLE
Add cudf (RAPIDS)

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#44]
https://github.com/rapidsai/cudf

**Comment by jangorecki** [comment]
As of now installation of rapids required anaconda which will heavily complicate reproducibility of this benchmark. Currently it is waiting for https://github.com/rapidsai/cudf/issues/331 to be solved

**Comment by mattdowle** [comment]
Do the suggestions in rapidsai/cudf#331 work?

**Comment by jangorecki** [comment]
@mattdowle It didn't, but I asked @abal5 for help in setting up environment. He finished his part, I just need to get back to that.

**Comment by jangorecki** [comment]
As of now we were unable to setup cudf. Soon it will hopefully be be easier once https://github.com/rapidsai/cudf/pull/567 will be resolved

**Comment by mattdowle** [comment]
That cudf issue 285 contains this comment : 

![image](https://user-images.githubusercontent.com/2779998/51289279-645af100-19b4-11e9-8bc2-bbcdff4c30e4.png)

That does not sound too bad. Did you try that and it failed with error messages?
The 2nd issue (567) was merged yesterday.

**Comment by jangorecki** [comment]
I successfully installed cuda toolkit 9.2 and trying on it, as cuda toolkit 10.0 was raising errors trying to access 9.2 shared libraries. Currently stuck on https://github.com/rapidsai/cudf/issues/736 @abal5

**Comment by jangorecki** [comment]
slowly moving forward, stuck on https://github.com/NVIDIA/nvstrings/issues/8

**Comment by jangorecki** [comment]
validation script need to be adjusted for appropriate tolerance: https://github.com/rapidsai/cudf/issues/2494

**Comment by jangorecki** [comment]
Current status is that q1-q5 are implemented, but unfortunately 1e8 and 1e9 are failing due to out of memory. 1e7 k=2 segfaults.

**Comment by jangorecki** [comment]
cuDF has been added to groupby benchmark fully, answers validated on 1e7, k=1e2 (head and tail).
I will close this issue once fresh run of benchmark timings will get published.
Pending issues related to cuDF:
- extend GPU memory to run cuDF for medium and big data #97
- investigate cuDF memory usage #94
- validation of chk should have tolerance within single solution #95
