### ISSUE TITLE
Add Gandiva/Dremio (arrow)

### ISSUE THREAD

**Issue by mattdowle** [h2oai/db-benchmark#49]
https://www.datanami.com/2018/11/28/dremio-donates-fast-analytics-compiler-to-apache-foundation

Here's an article with a benchmark.
https://www.dremio.com/gandiva-performance-improvements-production-query/

https://github.com/dremio/dremio-oss

**Comment by jangorecki** [comment]
From a brief read about this tool, it seems that its advantage could be eventually incorporated to pandas, as a part of arrow. In such a case I am not sure if the tool will bring some benefits here, in a field of time/memory efficiency. It has multiple other benefits related to data sourcing and ETL, but this is not what our benchmark is about. Moreover it is currently supported on RHEL and CentOS only. It is unknown to me if support for Debian/Ubuntu distrubution is on the roadmap as they do not have issues section open on github. I would close this issue, till Dremio gets support on Debian/Ubuntu, or at least we will know that Gandiva compiler responsible for speed is a distinct feature that will not eventually land in pandas.
