### ISSUE TITLE
run only solutions that have been upgraded since last run

### ISSUE THREAD

**Issue by jangorecki** [h2oai/db-benchmark#50]
as discussed in https://github.com/h2oai/db-benchmark/issues/12

**Comment by jangorecki** [comment]
implemented in https://github.com/h2oai/db-benchmark/commit/2b4d3bd8b91868d1fd66d674c6c13ee20fa39322
It tracks granularity per `nodename` (hostname), `solution`, `task`, `data`, `version`/`git`. If only single dataset was not run by a particular solution-task-data-version/git it should run it. Important to note that it compares vs run attempts, if some solution process got killed for particular version/git it will not try to repeat it.

**Comment by mattdowle** [comment]
By upgraded, do you mean there are has been a commit in dev (in which cases that's pretty much every day in most projects) or that a new version has been released?  I hope the former.  The idea is to get a rough idea of performance in dev as each product is updated in dev.
The other reason for repeating every day is to get a time series of measurements for the first run and second run.   For example,  it was very useful to see that data.table's second run is slower than the first run in some cases (a surprise).  It was useful to see that persist every day so we could tell it wasn't just a random glitch on one day. We can of course design a test to explicitly measure the 1st run performance (e.g. clearing os cache between each run, and starting a fresh R/Python session) and that would be best,  but for now we have limited resources, haven't implemented such a test yet and such a test would take longer to run -- it could be run once a week or something.

**Comment by jangorecki** [comment]
One of the first actions in benchmark run script we are upgrading all tools. After upgrade procedure finished we dumping version and git hash to VERSION and REVISION files for each solution. When we are approaching to run particular solution'a script we are checking current version from those files and compare to version reported in `time.csv` of the recent run for that _solution, task, data_ and run only those task and data (for each solution) where version is not the same as in reported timings. Note that version logged in `time.csv` is not taken from `VERSION`/`REVISION` files but requeried at the beginning of solution's script (although using same procedure as we use to produce `VERSION`/`REVISION`).
We currently check for devel releses only for data.table, pydatatable and dplyr. Other tools as upgraded from their repository where stable versions are published. Hanling building from source is big overhead, those tools does not publish devel releases in a way that is easy to upgrade (as in R). For pydt we build from source every time. Ideally would be to have documented way of installing nightly builds, for every solution, then at least we know it should brake.

**Comment by mattdowle** [comment]
Thanks. Have you ever managed to successfully install pandas, spark or dask development from source?
>  Handling building from source is big overhead, those tools does not publish devel releases in a way that is easy to upgrade
Does this mean it takes a long time to compile from source,  or does it mean it's very difficult such that you haven't managed to install from source at all.   I got the impression we were using latest dev versions of pandas, spark and dask in the past.  Was that not the case?

**Comment by jangorecki** [comment]
@mattdowle no, ideally to not increase already big maintenance cost to ask for development repositories. I tried pandas only, spark will be more difficult as you have to first compile spark, and then pyspark using your compiled spark. In the past we use devel spark but it was installed manually from published binaries.
re dplyr, when publishing report for a while I was only re-running specific tools, not all of them. Recently I run all of them but didn't yet published benchmark as there are exceptions that has to be resolved before.
