### ISSUE TITLE
Add JuliaDB

### ISSUE THREAD

**Issue by skanskan** [h2oai/db-benchmark#63]
It would be great to see also the results of JuliaDB or FastGroupBy.

**Comment by skanskan** [comment]
Sometimes is faster
https://discourse.julialang.org/t/group-by-performance-benchmarks-and-recommendations/9313

**Comment by skanskan** [comment]
I don't know how it works but maybe if the data is small enough JuliaDB will use  in-emory algos.

**Comment by jangorecki** [comment]
Even if it uses in-memory algos, in theory it shouldn't be faster than dataframes. At least when we will assume those projects are cooperating with each other. Ideally I would like juliadb to be re-used internally in dataframes when it runs out of memory. I will close this request for now, we can always re-open it in future. What would be escpecially encouring to re-open it are timings showing it is faster on our db-benchmark questions than DataFrames.jl.
