### ISSUE TITLE
report table adjustments: precision, sub-totals, naming

### ISSUE THREAD

**Issue by mattdowle** [h2oai/db-benchmark#67]
- [ ] Round up to whole seconds is plenty.  Including the 3 decimal digits (as now) just makes the table wider and harder to read.
- [x] The sub-totals don't really help. Could they be removed please.
- [ ] Could the table titles (product names) be repeated at the bottom after the total row.  Since when scrolling on a phone, the total figures are not displayed next to the product names and it's very hard to read.
- [x] Remove the 1st column (data) please.  The folk who want to click, see the data and reproduce for themselves,  will already be on the GitHub project page,  so those links can be there.
- [ ] "q1_grp.size" column title would be better "Rows per group"
- [x] "sorted" better as "Pre-sorted input?"  to convey that better.  "sorted" on it's own could mean sort the result or something (which it doesn't mean).

![image](https://user-images.githubusercontent.com/2779998/50362891-61d4bb00-051e-11e9-8a85-d6020a9e05c4.png)

**Comment by jangorecki** [comment]
> Round up to whole seconds is plenty. Including the 3 decimal digits (as now) just makes the table wider and harder to read.

Whole seconds are fine for 1e9, but for 1e7 we need at least 2 decimal digits. I could customize that by input size but prefer to keep it more generic, so eventually will be easier to adjust for other tasks.

> Could the table titles (product names) be repeated at the bottom after the total row. Since when scrolling on a phone, the total figures are not displayed next to the product names and it's very hard to read.

For that I think we need to change rendering process from `knitr::kable` to something else.

> "q1_grp.size" column title would be better "Rows per group"

"rows per group" might be misleading as it is valid for question 1.

**Comment by jangorecki** [comment]
Table has been moved from home page of benchmark into dedicated `groupby` task page. Formatting of that table is then a little less important as it was moved more in the background. My comments above regarding minor formatting changes stays valid. Closing that issue for now as format of the table is not high priority. Average time that user spends on website is small enough to focus to convey as much information in that small time frame.
