### ISSUE TITLE
Data I/O timings

### ISSUE THREAD

**Issue by MichaelChirico** [h2oai/db-benchmark#77]
Seeing all sorts of praise for `vroom` as being "faster" than `fread` recently.

It seems nobody is reading the small print -- `vroom` is just a lazy reader, which means that while I/O itself will feel fast, subsequent analysis will be (much?) slower... not to mention I presume it rates a 0 on robustness to non-cookie-cutter csvs.

It would be helpful to evaluate my suspicion quantitatively by building `vroom` into one of the pipelines here, not to mention it would be useful to include the start-up I/O costs of the other languages as well.

**Comment by jangorecki** [comment]
In benchmarks we are forcing evaluation so the whole benefits of laziness are being lost. Therefore I don't think we should focus on it, unless it is fast also when not lazy.

**Comment by MichaelChirico** [comment]
I think your second point gets more at what I had in mind, but I can't seem to articulate what exactly I have in mind, so closing for now.
