### ISSUE TITLE
Download data?

### ISSUE THREAD

**Issue by hadley** [h2oai/db-benchmark#87]
I'd love to be able to get the test data that you use, as well as the data underlying [the results](https://h2oai.github.io/db-benchmark/groupby.html). Are these available in the repo somewhere? I clicked around a bit, but I couldn't see anything obvious.

**Comment by jangorecki** [comment]
Data we are using are basically the same data as the one in [grouping benchmark from 2014](https://github.com/Rdatatable/data.table/wiki/Benchmarks-%3A-Grouping).
To generate data use [groupby-datagen.R](https://github.com/h2oai/db-benchmark/blob/master/groupby-datagen.R) script.
```sh
Rscript groupby-datagen.R 1e8 1e2 0 0
```
You might also find [repro.sh](https://github.com/h2oai/db-benchmark/blob/master/repro.sh) script useful.

----

Note that dplyr was performing significantly better before, which I reported in https://github.com/tidyverse/dplyr/issues/4334. Would be great if you could raise priority of this issue, so it can at least catch up with it previous speed.
To preview timings over time you can run the following code. There is git commit sha stored in timings logs so it can give more precise information at which point in git history performance regression has been introduced.
```r
library(data.table)
d = fread("https://h2oai.github.io/db-benchmark/time.csv", key="batch")[solution=="dplyr" & nodename=="mr-0xc11" & task=="groupby" & run==1L & data%like%"1e2_0_0"]
d = d[, .(batch=as.POSIXct(batch, origin="1970-01-01", tz="UTC"), data=factor(data), question=factor(question, levels=unique(question)), version, git, time_sec)]
lattice::xyplot(time_sec ~ batch | data, d, type="l", groups=question,
                xlab = "benchmark run", ylab = "seconds",
                scales=list(y=list(relation="free")), auto.key=list(points=FALSE, lines=TRUE))
```

![Rplot](https://user-images.githubusercontent.com/3627377/58066682-03346b80-7ba8-11e9-9ea6-247f4bbbf4ba.png)

**Comment by hadley** [comment]
It would be very useful to just have a link to download the data.

**Comment by jangorecki** [comment]
@hadley links are there on the report website https://h2oai.github.io/db-benchmark/ just below the plots, in Notes section

**Comment by hadley** [comment]
Ah ok, that makes sense. Thanks!
