### ISSUE TITLE
add Husky

### ISSUE THREAD

**Issue by xiaodaigh** [h2oai/db-benchmark#90]
see http://www.cse.cuhk.edu.hk/proj-h/research.html

**Comment by jangorecki** [comment]
@xiaodaigh thanks for suggestion. Do you have any better documentation than https://github.com/husky-team/husky/wiki/Aggregator?
ideally some examples that would correspond to our groupby task?

**Comment by xiaodaigh** [comment]
I have never used it. I posted an issue on their github. Hopefully to pitch
in

**Comment by jangorecki** [comment]
Husky project doesn't seems to be much active last year. I will close this issue, we can always re-open it in future if there will be really demand for it.
